### PR TITLE
Use the correct copyright statement in BUILD.gn

### PR DESCRIPTION
**Pull request by fmarier**

### CODE REVIEW

**Comment by fmarier** [comment]
cc @tmancey @ptigas

This looks like a Brave-specific makefile, not something that comes from Chromium. Am I mistaken?

**Comment by tmancey** [comment]
@fmarier That is correct, this is a Brave-specific makefile

**Comment by fmarier** [comment]
Thanks @tmancey. Would you mean reviewing and merging this PR in that case?

**Review by tmancey — APPROVED** [review]
LGTM++

**Pull request merged**
